[package]
name = "test_tracing"
version = "0.1.0"
authors = ["kristianwahlroos <kristian.whl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
